### ISSUE TITLE
grml-x (via grml-quickconfig) fails to start

### ISSUE THREAD

**Issue by jkirk** [grml/grml#20]
grml-x fails to start on Lenovo X250:

![signal-2017-05-05-140211](https://cloud.githubusercontent.com/assets/288637/25754005/fa3d6c4c-31bd-11e7-8d07-73457421c506.jpeg)

Seems like [libgl1-mesa-dri](https://packages.debian.org/stretch/libgl1-mesa-dri) is missing.

**Comment by mika** [comment]
Installing libgl1-mesa-dri adds 116MB(!) of additional disk space. :(
@flowolf - could you please verify whether running `au ; agi libgl1-mesa-dri` before trying to start X actually fixes this issue?

**Comment by flowolf** [comment]
tried on 
`4ac51d4f1096b43dcd4eeee756107c0df6980d2a  grml64-full_testing_build2025.iso`
did not work:
![img_20170509_115357](https://cloud.githubusercontent.com/assets/900893/25845507/7497f58c-34ae-11e7-9a4d-cd5528386b02.jpg)

**Comment by mika** [comment]
That's what I was afraid of, so problems with the
Would be interesting to see whether there are any further details in the xorg log file.
And I assume "grml-x --module vesa" works?

**Comment by flowolf** [comment]
nope. doesn't work.
![img_20170509_133349](https://cloud.githubusercontent.com/assets/900893/25848816/4c871d8a-34bc-11e7-83a8-07fadebff709.jpg)

**Comment by mika** [comment]
Oh wow, what does `/var/log/Xorg.0.log` tell? And which driver is in usage on your usual (Ubuntu IIRC) system?

**Comment by flowolf** [comment]
Xorg Output:
![img_20170509_135447](https://cloud.githubusercontent.com/assets/900893/25849769/10ef81a0-34c0-11e7-8a4d-3579f9cf584c.jpg)
![img_20170509_135452](https://cloud.githubusercontent.com/assets/900893/25849770/128840f6-34c0-11e7-8356-692a567dcc1a.jpg)

Ubuntu Xorg.0.log:
https://gist.github.com/flowolf/a6db065dc4c86e20968aa8eae3f31473

**Comment by xtaran** [comment]
Same on Lenovo Thinkpad T470s (amd64) and EeePC 900A (i386). Might be a general and not a hardware-specific issue.

**Comment by Head-on-a-Stick** [comment]
I get the same errors on a ThinkPad X201 but the graphical desktop will start if a shell is opened and these commands used:
`su - grml`
`grml-x` (or plain `startx`)

**Comment by mika** [comment]
Installation of xserver-xorg-video-intel package should fix the issue, please confirm whether this fixes your issue, otherwise reopen the bug. Thx!

**Comment by Head-on-a-Stick** [comment]
The Intel DDX driver does not fix the problem for me.

Xorg.0.log:

https://gist.github.com/Head-on-a-Stick/d43ae19c928200263887eeafd73b6d8e

As I mentioned, su'ing to the grml user and `startx`ing runs the desktop just fine so all the necessary packages are already installed.

The environmental variables differ between running `sudo -u grml env`, which give this:

https://gist.github.com/Head-on-a-Stick/172c56ad75e7ca03a461e8930758e28e

And using `su - grml` then `env`, which gives:

https://gist.github.com/Head-on-a-Stick/eedbc22e67fa5ab848efea38a0fdeb61

Perhaps the missing $XDG* stuff is the problem?

**Comment by mika** [comment]
Reopening the issue, thanks for the update @Head-on-a-Stick  - @jkirk do you have any idea about the permission stuff?

**Comment by xtaran** [comment]
JFTR: It didn't help on my Thinkpad T470s either.

**Comment by mika** [comment]
@xtaran is there anything in the logs or visible with the tty permissions which might shed light on what's the actual problem?

**Comment by flowolf** [comment]
current daily "auto-build2031 (2017-05-15)" still fails to start Xorg on X250.
and I installed xserver-xorg-video-intel.

Xorg.log here: https://gist.github.com/flowolf/56b308dfc4c225edcc0b34e1789734fa

**Comment by jkirk** [comment]
Thx for all the comments!

We have a couple of issues and details here. Please be aware that there are multiple ways to start X but we currently support only a few them (= these *should* work). (So please tell us how you start X in your reports. Thx!)

We have:

- "Start x" via `grml-quickconfig` (on tty1)
- Bootoption `startx`

Optionally we have
- `grml-x` as root (*not* recommended)
- `grml-x` as user grml (on tty5)
- `grml-x` as user grml
```
su - grml
grml-x`
```

What (currently) does *not* work (= is currently not supported):
- `sudo -u grml grml-x`
- grml-x out of GNU screen (on tty4)

We should create an issue for each of the supported ways (if they do not work). So to narrow down the problem, this issue should be about "Start x" via `grml-quickconfig`. That said, it is essential to know if X can be started generally on the target machine (with or without installing any additional packages). So please let us know. Thank you!

**Comment by mika** [comment]
@Head-on-a-Stick @flowolf @xtaran could you please read the comment by @jkirk and try to reproduce that and let us know what exactly fails and what works?

**Comment by Head-on-a-Stick** [comment]
(Sorry for the delay)

I tried all of the suggested methods on my ThinkPad X201, the only working solutions are to use `grml-x` as root or to `su - grml` and then either `startx` or `grml-x`

Here are the log files:

Bootoption `startx` https://gist.github.com/Head-on-a-Stick/c3886d4ad9cdabcaf564d793b2a07c56

`startx` via `grml-quickconfig` (tty1) https://gist.github.com/Head-on-a-Stick/b168b5f0eb73e1b7858aab2531289743

`grml-x` from GNU screen (tty4) https://gist.github.com/Head-on-a-Stick/394016c2a500eea840d02d8c1f440b5b

`grml-x` as user grml (tty5) https://gist.github.com/Head-on-a-Stick/509de12a269550f5e1b411ecdd6cd201

No additional packages have been installed, this was all from a fresh boot of the live image.

**Comment by jkirk** [comment]
Thank you all for your comments, debugging and logs. They were very helpful. We can say now, that this is not a driver problem, but mostly a permission and systemd issue and I think I have a solution for this. As soon as my PRs got merged I would love to here your experience with following daily image. Thx, guys!

**Comment by mika** [comment]
We'd appreciate if anyone of you could verify that it's working as intended, daily ISOs starting with build grml64-full_testing_build2042.iso (https://daily.grml.org/grml64-full_testing/2017-05-25_04-25-15/grml64-full_testing_build2042.iso) are supposed to be working fine.

**Comment by Head-on-a-Stick** [comment]
I can confirm that the GRUB menu option to boot straight to the graphical desktop works just fine with build 2044, user grml has autologin & grml-x on tty7 as expected.

However, if the system is booted with the default GRUB entry then the "Start x" shortcut in `grml-quickconfig` still fails with the same log contents as before.

**Comment by mika** [comment]
@Head-on-a-Stick ah, indeed - good catch, thanks for reporting! This should be fixed now with the latest change, I'll verify on my own that this works as intended, though for sure appreciate your feedback too, the daily ISO as of tomorrow (2017-05-29) is supposed to include the fix. Thx!

**Comment by flowolf** [comment]
build 2046 works (Lenovo X250)
startx with root and grml user, out of grml-quickconfig, with boot option.

**Comment by mika** [comment]
Jey, thanks for verification - @flowolf :+1:
